/**
 * Catégories de pièces automobiles pour la navigation catalogue
 */
export const PART_CATEGORIES = [
  'Freinage',
  'Filtration',
  'Suspension',
  'Embrayage',
  'Distribution',
  'Allumage',
  'Éclairage',
  'Refroidissement',
  'Échappement',
  'Direction',
  'Transmission',
  'Carrosserie',
  'Électrique',
  'Moteur',
  'Accessoires',
] as const

export type PartCategory = (typeof PART_CATEGORIES)[number]

/**
 * Hiérarchie catégorie → sous-catégories de pièces (style RockAuto)
 * Utilisé pour la sélection lors de l'ajout de pièces au catalogue.
 */
export const PART_CATALOG: Record<PartCategory, string[]> = {
  Freinage: [
    'Plaquettes de frein',
    'Disques de frein',
    'Étriers de frein',
    'Tambours de frein',
    'Mâchoires de frein',
    'Maître-cylindre',
    'Liquide de frein',
    'Flexibles de frein',
    'Capteur ABS',
    'Câble de frein à main',
  ],
  Filtration: [
    'Filtre à huile',
    'Filtre à air',
    'Filtre à carburant',
    'Filtre à gasoil',
    "Filtre d'habitacle",
    'Filtre à particules',
  ],
  Suspension: [
    'Amortisseur avant',
    'Amortisseur arrière',
    'Ressort de suspension',
    'Triangle de suspension',
    'Rotule de suspension',
    'Silentbloc',
    'Barre stabilisatrice',
    'Biellette de barre stab',
    'Coupelle d\'amortisseur',
  ],
  Embrayage: [
    'Kit d\'embrayage',
    'Disque d\'embrayage',
    'Mécanisme d\'embrayage',
    'Butée d\'embrayage',
    'Volant moteur',
    'Récepteur d\'embrayage',
    'Émetteur d\'embrayage',
  ],
  Distribution: [
    'Kit de distribution',
    'Courroie de distribution',
    'Chaîne de distribution',
    'Galet tendeur',
    'Galet enrouleur',
    'Pompe à eau',
  ],
  Allumage: [
    'Bougies d\'allumage',
    'Bougies de préchauffage',
    'Bobine d\'allumage',
    'Câbles d\'allumage',
    'Démarreur',
    'Alternateur',
    'Batterie',
  ],
  'Éclairage': [
    'Phare avant',
    'Feu arrière',
    'Clignotant',
    'Ampoule H4',
    'Ampoule H7',
    'Ampoule LED',
    'Antibrouillard',
    'Feu de plaque',
  ],
  Refroidissement: [
    'Radiateur',
    'Ventilateur de radiateur',
    'Thermostat',
    'Pompe à eau',
    'Vase d\'expansion',
    'Durite de radiateur',
    'Bouchon de radiateur',
    'Liquide de refroidissement',
  ],
  'Échappement': [
    'Pot d\'échappement',
    'Silencieux',
    'Catalyseur',
    'Sonde lambda',
    'Collecteur d\'échappement',
    'Tuyau d\'échappement',
    'Joint d\'échappement',
  ],
  Direction: [
    'Crémaillère de direction',
    'Pompe de direction assistée',
    'Biellette de direction',
    'Rotule de direction',
    'Soufflet de direction',
    'Volant',
  ],
  Transmission: [
    'Cardan',
    'Soufflet de cardan',
    'Joint homocinétique',
    'Roulement de roue',
    'Boîte de vitesses',
    'Arbre de transmission',
  ],
  Carrosserie: [
    'Pare-chocs avant',
    'Pare-chocs arrière',
    'Capot',
    'Aile avant',
    'Porte',
    'Rétroviseur',
    'Pare-brise',
    'Lunette arrière',
    'Calandre',
    'Poignée de porte',
  ],
  'Électrique': [
    'Faisceau électrique',
    'Fusibles',
    'Relais',
    'Capteur de température',
    'Capteur de position vilebrequin',
    'Capteur de position arbre à cames',
    'Débitmètre d\'air',
    'Sonde lambda',
    'Calculateur moteur',
  ],
  Moteur: [
    'Joint de culasse',
    'Joint de carter',
    'Pistons',
    'Segments',
    'Coussinets de vilebrequin',
    'Pompe à huile',
    'Huile moteur',
    'Soupapes',
    'Injecteurs',
    'Pompe d\'injection',
    'Turbo',
  ],
  Accessoires: [
    'Tapis de sol',
    'Housse de siège',
    'Volant sport',
    'Pommeau de levier',
    'Antivol',
    'Chargeur USB',
    'Support téléphone',
    'Désodorisant',
  ],
}
