/**
 * Catégories de pièces automobiles pour la navigation catalogue
 */
export const PART_CATEGORIES = [
  'Moteur',
  'Distribution',
  'Allumage',
  'Alimentation carburant',
  'Admission & turbo',
  'Échappement',
  'Refroidissement',
  'Lubrification',
  'Filtration',
  'Embrayage',
  'Transmission',
  'Boîte de vitesses',
  'Freinage',
  'Suspension',
  'Direction',
  'Roues & pneus',
  'Électrique & batterie',
  'Démarrage & charge',
  'Capteurs & calculateurs',
  'Éclairage & signalisation',
  'Climatisation & chauffage',
  'Essuie-glace & lave-glace',
  'Vitrage',
  'Carrosserie extérieure',
  'Carrosserie intérieure',
  'Sièges & sellerie',
  'Serrurerie & sécurité',
  'Audio & multimédia',
  'Navigation & connectivité',
  'Accessoires & équipements',
  'Outillage & entretien',
  'Fluides & consommables',
] as const

export type PartCategory = (typeof PART_CATEGORIES)[number]

/**
 * Hiérarchie catégorie → sous-catégories de pièces (style RockAuto)
 * Utilisé pour la sélection lors de l'ajout de pièces au catalogue.
 */
export const PART_CATALOG: Record<PartCategory, string[]> = {
  Moteur: [
    'Bloc moteur complet',
    'Culasse',
    'Joint de culasse',
    'Joint de carter',
    'Pistons',
    'Segments de piston',
    'Bielles',
    'Vilebrequin',
    'Arbre à cames',
    'Poussoirs hydrauliques',
    'Soupapes admission',
    'Soupapes échappement',
    'Ressorts de soupape',
    'Guide de soupape',
    'Coussinets de vilebrequin',
    'Coussinets de bielle',
    'Pompe à huile',
    'Carter d\'huile',
    'Carter moteur',
    'Support moteur',
    'Silentbloc moteur',
    'Cache culbuteurs',
    'Cache moteur',
    'Pièces détachées moteur autres',
  ],
  Distribution: [
    'Kit de distribution complet',
    'Courroie de distribution',
    'Chaîne de distribution',
    'Galet tendeur',
    'Galet enrouleur',
    'Pignon de distribution',
    'Tendeur hydraulique',
    'Amortisseur de chaîne',
    'Kit chaîne + pignons',
    'Pompe à eau (distribution)',
  ],
  Allumage: [
    'Bougies d\'allumage',
    'Bougies de préchauffage',
    'Bobine d\'allumage',
    'Câbles d\'allumage',
    'Tête de delco',
    'Rotor d\'allumeur',
    'Module d\'allumage',
    'Capteur de cliquetis',
  ],
  'Alimentation carburant': [
    'Pompe à carburant',
    'Pompe d\'injection',
    'Injecteurs essence',
    'Injecteurs diesel',
    'Rampe commune (common rail)',
    'Régulateur de pression carburant',
    'Réservoir de carburant',
    'Bouchon de réservoir',
    'Jauge de carburant',
    'Durite carburant',
    'Filtre à carburant',
    'Filtre à gasoil',
  ],
  'Admission & turbo': [
    'Collecteur d\'admission',
    'Papillon des gaz',
    'Débitmètre d\'air',
    'Corps de papillon',
    'Capteur MAP',
    'Turbo / turbocompresseur',
    'Intercooler / échangeur',
    'Durite d\'admission',
    'Vanne EGR',
    'Boîtier papillon',
    'Actuateur de turbo',
  ],
  'Échappement': [
    'Collecteur d\'échappement',
    'Ligne d\'échappement complète',
    'Catalyseur',
    'Filtre à particules (FAP)',
    'Silencieux avant',
    'Silencieux intermédiaire',
    'Silencieux arrière',
    'Tuyau d\'échappement',
    'Sonde lambda',
    'Joint d\'échappement',
    'Bride d\'échappement',
    'Support d\'échappement',
  ],
  Refroidissement: [
    'Radiateur de refroidissement',
    'Ventilateur de radiateur',
    'Moteur ventilateur',
    'Thermostat',
    'Boîtier de thermostat',
    'Pompe à eau',
    'Vase d\'expansion',
    'Bouchon de radiateur',
    'Bouchon de vase',
    'Durite supérieure',
    'Durite inférieure',
    'Durite de chauffage',
    'Sonde de température',
    'Capteur de température',
    'Liquide de refroidissement',
  ],
  Lubrification: [
    'Pompe à huile',
    'Crépine d\'huile',
    'Jauge d\'huile',
    'Bouchon de vidange',
    'Joint de bouchon',
    'Manocontact d\'huile',
    'Refroidisseur d\'huile',
    'Huile moteur',
    'Huile boîte',
    'Huile de direction',
  ],
  Filtration: [
    'Filtre à huile',
    'Filtre à air',
    'Filtre à carburant',
    'Filtre à gasoil',
    "Filtre d'habitacle",
    'Filtre à particules',
    'Filtre de boîte automatique',
  ],
  Embrayage: [
    'Kit d\'embrayage complet',
    'Disque d\'embrayage',
    'Mécanisme d\'embrayage',
    'Butée d\'embrayage',
    'Butée hydraulique',
    'Volant moteur bi-masse',
    'Volant moteur mono-masse',
    'Émetteur d\'embrayage',
    'Récepteur d\'embrayage',
    'Câble d\'embrayage',
    'Pédale d\'embrayage',
  ],
  Transmission: [
    'Cardan complet',
    'Soufflet de cardan',
    'Joint homocinétique',
    'Tripode',
    'Arbre de transmission',
    'Croisillon',
    'Support de cardan',
    'Roulement de roue avant',
    'Roulement de roue arrière',
    'Moyeu de roue',
  ],
  'Boîte de vitesses': [
    'Boîte manuelle complète',
    'Boîte automatique complète',
    'Levier de vitesses',
    'Pommeau de levier',
    'Soufflet de levier',
    'Tringlerie de boîte',
    'Synchros',
    'Fourchette de boîte',
    'Axes de fourchette',
    'Capteur de vitesse',
    'Capteur de régime boîte',
    'Huile de boîte',
  ],
  Freinage: [
    'Plaquettes avant',
    'Plaquettes arrière',
    'Disques avant',
    'Disques arrière',
    'Étrier avant',
    'Étrier arrière',
    'Tambours',
    'Mâchoires',
    'Maître-cylindre',
    'Cylindre de roue',
    'Servofrein',
    'Liquide de frein',
    'Flexibles de frein',
    'Tuyaux rigides',
    'Capteur ABS avant',
    'Capteur ABS arrière',
    'Bloc ABS',
    'Frein à main complet',
    'Câble de frein à main',
    'Levier de frein à main',
    'Témoin d\'usure',
  ],
  Suspension: [
    'Amortisseur avant',
    'Amortisseur arrière',
    'Ressort avant',
    'Ressort arrière',
    'Combiné fileté',
    'Triangle avant',
    'Triangle arrière',
    'Rotule de suspension',
    'Silentbloc',
    'Barre stabilisatrice',
    'Biellette de barre stabilisatrice',
    'Coupelle d\'amortisseur',
    'Butée d\'amortisseur',
    'Soufflet d\'amortisseur',
    'Berceau',
    'Bras oscillant',
  ],
  Direction: [
    'Crémaillère de direction',
    'Pompe de direction assistée',
    'Réservoir direction assistée',
    'Biellette de direction',
    'Rotule de direction',
    'Soufflet de crémaillère',
    'Volant',
    'Colonne de direction',
    'Cardan de direction',
    'Capteur d\'angle volant',
    'Moteur de direction assistée',
  ],
  'Roues & pneus': [
    'Jante acier',
    'Jante alu',
    'Pneu été',
    'Pneu hiver',
    'Pneu toutes saisons',
    'Chambre à air',
    'Écrou de roue',
    'Boulon de roue',
    'Clé antivol',
    'Équilibreuse (masses)',
    'Valve de roue',
    'Capteur pression pneus (TPMS)',
    'Enjoliveur',
    'Roue de secours',
  ],
  'Électrique & batterie': [
    'Batterie',
    'Cosse de batterie',
    'Coupe-circuit',
    'Faisceau électrique moteur',
    'Faisceau électrique habitacle',
    'Fusibles',
    'Boîte à fusibles',
    'Relais',
    'Contacteur',
    'Prise allume-cigare',
    'Prise USB',
    'Contact',
    'Convertisseur',
    'Câbles de démarrage',
  ],
  'Démarrage & charge': [
    'Démarreur',
    'Alternateur',
    'Régulateur d\'alternateur',
    'Poulie d\'alternateur',
    'Courroie d\'accessoires',
    'Galet accessoires',
    'Solénoïde de démarreur',
    'Lanceur de démarreur',
  ],
  'Capteurs & calculateurs': [
    'Calculateur moteur (ECU)',
    'Calculateur boîte',
    'Calculateur ABS',
    'Calculateur airbag',
    'Capteur vilebrequin',
    'Capteur arbre à cames',
    'Capteur PMH',
    'Débitmètre d\'air',
    'Sonde lambda amont',
    'Sonde lambda aval',
    'Capteur MAP',
    'Capteur MAF',
    'Capteur de cliquetis',
    'Capteur de pression',
    'Capteur de température',
    'Capteur de niveau',
  ],
  'Éclairage & signalisation': [
    'Phare avant gauche',
    'Phare avant droit',
    'Feu arrière gauche',
    'Feu arrière droit',
    'Feu antibrouillard avant',
    'Feu antibrouillard arrière',
    'Feu de plaque',
    'Feu stop central',
    'Clignotant avant',
    'Clignotant arrière',
    'Clignotant latéral',
    'Ampoule H1',
    'Ampoule H3',
    'Ampoule H4',
    'Ampoule H7',
    'Ampoule H11',
    'Ampoule LED',
    'Ampoule xénon',
    'Ampoule de plafonnier',
    'Avertisseur sonore (klaxon)',
    'Optique de phare',
    'Cache phare',
    'Moteur de lève-phare',
  ],
  'Climatisation & chauffage': [
    'Compresseur de clim',
    'Condenseur de clim',
    'Évaporateur',
    'Détendeur de clim',
    'Pressostat',
    'Radiateur de chauffage',
    'Pulseur d\'air',
    'Résistance de pulseur',
    'Filtre d\'habitacle',
    'Volet d\'air',
    'Panneau de commande clim',
    'Sonde de température habitacle',
    'Bouteille déshydratante',
    'Fluide frigorigène',
  ],
  'Essuie-glace & lave-glace': [
    'Balai d\'essuie-glace avant',
    'Balai d\'essuie-glace arrière',
    'Moteur d\'essuie-glace',
    'Bras d\'essuie-glace',
    'Biellette d\'essuie-glace',
    'Pompe de lave-glace',
    'Gicleur',
    'Réservoir lave-glace',
    'Liquide lave-glace',
    'Joint de réservoir',
  ],
  Vitrage: [
    'Pare-brise',
    'Lunette arrière',
    'Vitre avant gauche',
    'Vitre avant droite',
    'Vitre arrière gauche',
    'Vitre arrière droite',
    'Vitre custode',
    'Lève-vitre avant',
    'Lève-vitre arrière',
    'Moteur de lève-vitre',
    'Joint de pare-brise',
    'Rétroviseur gauche',
    'Rétroviseur droit',
    'Coque de rétroviseur',
    'Glace de rétroviseur',
    'Rétroviseur intérieur',
  ],
  'Carrosserie extérieure': [
    'Pare-chocs avant',
    'Pare-chocs arrière',
    'Capot',
    'Aile avant gauche',
    'Aile avant droite',
    'Aile arrière',
    'Porte avant gauche',
    'Porte avant droite',
    'Porte arrière gauche',
    'Porte arrière droite',
    'Hayon / coffre',
    'Calandre / grille',
    'Logo / emblème',
    'Baguette de protection',
    'Passage de roue',
    'Tôle de bas de caisse',
    'Antenne',
    'Support antenne',
    'Joint de portière',
    'Seuil de porte',
    'Traverse avant',
  ],
  'Carrosserie intérieure': [
    'Tableau de bord complet',
    'Combiné d\'instruments',
    'Compteur de vitesse',
    'Compte-tours',
    'Console centrale',
    'Garniture de porte',
    'Garniture de coffre',
    'Ciel de toit',
    'Pare-soleil',
    'Poignée de porte intérieure',
    'Bouton de commande',
    'Levier de clignotant',
    'Commodo',
    'Rosace de volant',
    'Cache airbag',
    'Airbag conducteur',
    'Airbag passager',
    'Airbag rideau',
    'Airbag latéral',
    'Prétensionneur de ceinture',
    'Tapis de sol',
  ],
  'Sièges & sellerie': [
    'Siège conducteur complet',
    'Siège passager complet',
    'Banquette arrière',
    'Appui-tête',
    'Housse de siège',
    'Rail de siège',
    'Ceinture de sécurité',
    'Boucle de ceinture',
    'Moteur de siège électrique',
    'Commande de siège',
  ],
  'Serrurerie & sécurité': [
    'Serrure de porte avant',
    'Serrure de porte arrière',
    'Serrure de hayon',
    'Serrure de capot',
    'Barillet',
    'Télécommande de clé',
    'Boîtier télécommande',
    'Clé brute',
    'Clé de contact',
    'Actionneur centralisation',
    'Pompe de centralisation',
    'Antivol / alarme',
    'Antidémarrage',
  ],
  'Audio & multimédia': [
    'Autoradio d\'origine',
    'Autoradio 1 DIN',
    'Autoradio 2 DIN',
    'Autoradio Android Auto / CarPlay',
    'Amplificateur',
    'Haut-parleur avant',
    'Haut-parleur arrière',
    'Subwoofer',
    'Tweeter',
    'Antenne radio',
    'Lecteur CD',
    'Écran tactile',
    'Commande au volant',
  ],
  'Navigation & connectivité': [
    'GPS intégré',
    'Module Bluetooth',
    'Caméra de recul',
    'Écran caméra de recul',
    'Radar de recul',
    'Dashcam',
    'Chargeur induction',
    'Support téléphone',
  ],
  'Accessoires & équipements': [
    'Tapis de coffre',
    'Barre de toit',
    'Coffre de toit',
    'Porte-vélo',
    'Attelage',
    'Faisceau attelage',
    'Chaînes à neige',
    'Triangle de signalisation',
    'Gilet haute visibilité',
    'Extincteur',
    'Trousse de secours',
    'Protection de seuil',
    'Déflecteur',
  ],
  'Outillage & entretien': [
    'Cric',
    'Manivelle',
    'Clé en croix',
    'Démonte-pneu',
    'Compresseur portable',
    'Testeur batterie',
    'OBD / valise diagnostic',
    'Multimètre',
    'Kit anti-crevaison',
  ],
  'Fluides & consommables': [
    'Huile moteur',
    'Huile de boîte manuelle',
    'Huile de boîte automatique (ATF)',
    'Huile de différentiel',
    'Liquide de frein DOT 3',
    'Liquide de frein DOT 4',
    'Liquide de frein DOT 5.1',
    'Liquide de refroidissement',
    'Liquide de direction assistée',
    'Liquide lave-glace',
    'Additif carburant',
    'Dégrippant',
    'Nettoyant frein',
    'Graisse',
    'Silicone étanchéité',
  ],
}
