export { ABIDJAN_COMMUNES } from './communes'
export type { AbidjanCommune } from './communes'
export { VEHICLE_BRANDS, VEHICLE_DATA, BRAND_NAMES, getEngines } from './vehicles'
export { PART_CATEGORIES, PART_CATALOG } from './categories'
export type { PartCategory } from './categories'
